
  
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_FORGOTPASSWORD_REQUEST = 'ADMIN_FORGOTPASSWORD_REQUEST'
export const ADMIN_FORGOTPASSWORD_SUCCESS = 'ADMIN_FORGOTPASSWORD_SUCCESS'
export const ADMIN_FORGOTPASSWORD_FAIL = 'ADMIN_FORGOTPASSWORD_FAIL'
export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST'
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS'
export const NOTIFICATION_FAIL = 'NOTIFICATION_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'